### ISSUE TITLE
Проработка архитектуры

### ISSUE THREAD

**Issue by batchar2** [batchar2/octopus#3]
Нужно напряч извилины и родить архитектуру для обработки запроса от клиента в клиенском приложении (парсинг пакета данных,  авторизация) - передача ядру системы результатов,  хранение ключей. Вопрос требует серьезной проработки.

**Comment by batchar2** [comment]
Имхо подсказывает,  что-то похожее на "абстрактную фабрику"  и "команду". Порождаем объекты и сливаем рули управления связанными классами.

**Comment by batchar2** [comment]
Либо "строитель" и опять-же "команда". Строим объект по запросу,  преобразовываем если нужно (первичное дешифрование) - через команду  обработчик для этого подсовываем. Таким же образом через команду пост обработка сообщения - пересылка ядру,  либо генерация ключа или идентификатора сессии и прочее.  А что в команду завернуть, какой обработчик - это не важно,  с точки зрения интерфейся.

**Comment by NSusoev** [comment]
Думаю, остановиться на варианте фабричного метода и команды - самое оно

**Comment by batchar2** [comment]
Реализовал.  Смотри.  

Фабричный метод идентифицируется по типу пакета. Дергает соответствующий "построитель" (тип пакета - ключ в словаре, в котором приведены "построители"). Этот "построитель", после преобразования буфера к нужному виду пакета, сливает пакет данных обработчику "команде". Эта команда выполняет построение ответного пакета, она связана с клиенским процессом, к которому периодически обращается (отправить  данные, сгенерировать ключи и прочее). см.код
